### ISSUE TITLE
Get rid of irtkVTKFunctions

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/irtk-refactored-deprecated#1]
The header file only includes a bunch of VTK headers and is in turn included by the module header irtkGeometry.h. It also only defines a single function, GetConnectedVertices, which I cannot find to be used anywhere. The msample.cc application defines its own GetConnectedVertices function. ~~Worst of all, the GetConnectedVertices function is terribly implemented and extremely inefficient. The vtkPolyData class provides a more efficient method to get all cells connected to a point vtkPolyData::GetPointCells after vtkPolyData::BuildLinks has been called.~~ The PolyData module further provides an auxiliary class irtkEdgeTable that can be used to get all adjacent points or iterate efficiently over all edges. It is on the other hand less efficient if the list of adjacencies is only needed for a few points. But irtkEdgeTable could be extended with a public static function that allows to obtain such list for a single point without constructing the entire table.

**Comment by schuhschuh** [comment]
I just had another look at the function. It is indeed using vtkPolyData::GetPointCells! So I guess the issue is rather to make this global function a static member function of irtkEdgeTable and then remove the more or less empty irtkVTKFunctions header file.

**Comment by ghisvail** [comment]
Good. Since you already have a definitive solution in mind, please consider submitting a PR for it.

**Comment by schuhschuh** [comment]
Ready to be committed, just need to wait for the pending PR's to be merged so I can rebase my feature branch to send a PR with changes only related to this issue.

**Comment by ghisvail** [comment]
Closed by 134855b
