### ISSUE TITLE
Replace usage of deprecated auto_ptr

### ISSUE THREAD

**Issue by ghisvail** [BioMedIA/irtk-refactored-deprecated#11]
Since we now require compiler support for C++11, deprecation warnings show up with regards to our usage of `auto_ptr`. These should be replaced by either `std::shared_ptr` or `std::unique_ptr` depending on what was the intended scope of the smart pointer.

**Comment by schuhschuh** [comment]
All uses of `auto_ptr` are most likely in my code and the use case is always the one of a `unique_ptr` mainly within the main source file of command-line tools.
