### ISSUE TITLE
Compilation error when linking with VTK 5.10

### ISSUE THREAD

**Issue by stefanpsz** [BioMedIA/irtk-refactored-deprecated#17]
When linking with VTK 5.10, the following compilation error arises:

[ 80%] Building CXX object Modules/Registration/src/CMakeFiles/Registration.dir/irtkRegisteredPointSet.cc.o
In file included from /usr/include/c++/5/backward/strstream:51:0,
                 from /usr/include/vtk-5.10/vtkIOStream.h:108,
                 from /usr/include/vtk-5.10/vtkSystemIncludes.h:40,
                 from /usr/include/vtk-5.10/vtkIndent.h:24,
                 from /usr/include/vtk-5.10/vtkObjectBase.h:43,
                 from /usr/include/vtk-5.10/vtkSmartPointerBase.h:26,
                 from /usr/include/vtk-5.10/vtkSmartPointer.h:23,
                 from /data/workspace/IRTK/Modules/Registration/include/irtkRegisteredPointSet.h:20,
                 from /data/workspace/IRTK/Modules/Registration/src/irtkRegisteredPointSet.cc:17:
/usr/include/c++/5/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^
/data/workspace/IRTK/Modules/Registration/src/irtkPointSetForce.cc: In member function ‘vtkDataArray\* irtkPointSetForce::AddPointData(const char*, int, int)’:
/data/workspace/IRTK/Modules/Registration/src/irtkPointSetForce.cc:165:22:  error : ‘class vtkDataArray’ has no member named ‘GetArrayType’
   if (!data || data->GetArrayType() != type || data->GetNumberOfComponents() != c) {
                      ^

**Comment by schuhschuh** [comment]
Hi Stefan, a look at the installation instructions reveals that the new IRTK will no longer support VTK 5. You need to use VTK 6.

**Comment by jopasserat** [comment]
Ain't there a way to require VTK >= 6 in CMake?

**Comment by ghisvail** [comment]
I believe I tried `find_package(VTK VERSION 6)` but it only succeeds with an exact version match. Can someone please confirm this ?

Anyway VTK also exports its MAJOR and MINOR versions, so we can just check these.

**Comment by schuhschuh** [comment]
To my knowledge, this should work fine as long as you don't also pass the `EXACT` option to `find_package`. Here's the code from the generated `VTKConfigVersion.cmake`:

``` cmake
if("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}" )
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()

  if("6.3.0" MATCHES "^([0-9]+)\\.")
    set(CVF_VERSION_MAJOR "${CMAKE_MATCH_1}")
  else()
    set(CVF_VERSION_MAJOR "6.3.0")
  endif()

  if("${PACKAGE_FIND_VERSION_MAJOR}" STREQUAL "${CVF_VERSION_MAJOR}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  endif()

  if( "${PACKAGE_FIND_VERSION}" STREQUAL "${PACKAGE_VERSION}")
      set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
```

The first if test is important. Maybe CMake's `VERSION_LESS` if operator needs a version string in the format `6.0.0`?

**Comment by schuhschuh** [comment]
You could easily test with a CMake script:

``` cmake
if ("6.3.0" VERSION_LESS "6")
  message(FATAL_ERROR "Screw CMake")
else ()
  message("Hurray")
endif ()
```

`cmake -P test_version_less.cmake`

And the output is:

```
> cmake -P test_version_less.cmake 
Hurray
```

**Comment by schuhschuh** [comment]
Ah, I think the issue might indeed be the following CMake code VTK uses:

``` cmake
  if("${PACKAGE_FIND_VERSION_MAJOR}" STREQUAL "${CVF_VERSION_MAJOR}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  endif()
```

If CMake, obtains the `PACKAGE_FIND_VERSION_MAJOR` in the same way as they do here with a regex that expects to find a dot in the version string (i.e., `^([0-9]+)\\.`).

Try `find_package(VTK VERSION 6.0.0)`.

**Comment by schuhschuh** [comment]
According to the CMake documentation, there is no `VERSION` keyword and "6" as version string should be fine, i.e., `find_package(VTK 6)`.

**Comment by ghisvail** [comment]
Ok, will test Andreas' solution tomorrow. We need to make sure this works on CMake `2.8.12` at least, which is the one shipped by the Ubuntu LTS.

**Comment by schuhschuh** [comment]
I had a look at the CMake 2.8.12 documentation and the signature of `find_package` has not changed.

**Comment by ghisvail** [comment]
Good.

**Comment by ghisvail** [comment]
FYI, applying the following diff:

```
diff --git a/CMake/IRTKBuildDeps.cmake b/CMake/IRTKBuildDeps.cmake
index 52ba008..f4aea78 100644
--- a/CMake/IRTKBuildDeps.cmake
+++ b/CMake/IRTKBuildDeps.cmake
@@ -47,7 +47,7 @@ if(WITH_VTK)
                      vtkIOLegacy
                      vtkIOPLY
                      vtkIOXML)
-  find_package(VTK COMPONENTS ${VTK_COMPONENTS} NO_MODULE REQUIRED)
+  find_package(VTK 6 COMPONENTS ${VTK_COMPONENTS} NO_MODULE REQUIRED)
   include_directories(${VTK_INCLUDE_DIRS})
   link_libraries(${VTK_LIBRARIES})
   add_definitions(-DHAS_VTK -DHAVE_VTK)
```

leads to:

```
cmake -DWITH_VTK=ON ..
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   math_c99
CMake Error at CMake/IRTKBuildDeps.cmake:50 (find_package):
  Could not find a configuration file for package "VTK" that is compatible
  with requested version "6".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/vtk-6.1/VTKConfig.cmake, version: 6.1.0

Call Stack (most recent call first):
  CMakeLists.txt:30 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by schuhschuh** [comment]
I suggest you add a print statement to  /usr/lib/cmake/vtk-6.1/VTKConfigVersion.cmake to see what the value of PACKAGE_FIND_VERSION_MAJOR and PACKAGE_FIND_VERSION is.

**Comment by ghisvail** [comment]
This, on the other hand, appears to work:

```
diff --git a/CMake/IRTKBuildDeps.cmake b/CMake/IRTKBuildDeps.cmake
index 52ba008..4f58170 100644
--- a/CMake/IRTKBuildDeps.cmake
+++ b/CMake/IRTKBuildDeps.cmake
@@ -48,6 +48,9 @@ if(WITH_VTK)
                      vtkIOPLY
                      vtkIOXML)
   find_package(VTK COMPONENTS ${VTK_COMPONENTS} NO_MODULE REQUIRED)
+  if("${VTK_VERSION_MAJOR}.${VTK_VERSION_MINOR}" VERSION_LESS 6.0)
+    message(FATAL_ERROR "IRTK requires VTK version 6")
+  endif()
   include_directories(${VTK_INCLUDE_DIRS})
   link_libraries(${VTK_LIBRARIES})
   add_definitions(-DHAS_VTK -DHAVE_VTK)
```

EDIT: typos

**Comment by schuhschuh** [comment]
If nothing else works, ok. But I would still debug in VTKConfigVersion.cmake to see why it claims to be not compatible.

**Comment by ghisvail** [comment]
Go ahead

**Comment by schuhschuh** [comment]
I think you are on it. Doesn't take much more effort.

EDIT: The solution you propose is a hack, not a real fix. If somebody has both VTK 5 and VTK 6 installed, CMake would be able to find VTK 6 still if you use the right `find_package` syntax. Not the case with your hack. It might just find VTK 5 and think it's done. When the issue is a bug in CMake, then at least use the hack only for older CMake versions, but not newer ones without the bug.

**Comment by ghisvail** [comment]
Do we have the same content of `VTKConfig.cmake` ? Mine reads:

```
# The full VTK version number.
SET(PACKAGE_VERSION "6.1.0")

# This version is compatible only with matching major.minor versions.
IF("6.1" VERSION_EQUAL "${PACKAGE_FIND_VERSION_MAJOR}.${PACKAGE_FIND_VERSION_MINOR}")
  # This version is compatible with equal or lesser patch versions.
  IF(NOT "0" VERSION_LESS "${PACKAGE_FIND_VERSION_PATCH}")
    SET(PACKAGE_VERSION_COMPATIBLE 1)
    IF("0" VERSION_EQUAL "${PACKAGE_FIND_VERSION_PATCH}")
      SET(PACKAGE_VERSION_EXACT 1)
    ENDIF()
  ENDIF()
ENDIF()
```

For the first few lines, and the comment is quite explicit. Version 6.1 is **not** compatible with 6.0. Or am I missing something ?

**Comment by schuhschuh** [comment]
Does seem so. In that case we should require at least VTK 6.1.

**Comment by ghisvail** [comment]
Maybe I did not insist enough on the compatibility with the current Ubuntu LTS. VTK is stuck at version 6.0 there.

Which features do we require from 6.1? I was able to build fine with 6.0 last time I checked.

**Comment by schuhschuh** [comment]
It should be fine to use VTK 6.0. Was just thinking if they messed sth up in this version and therefore the strict compatibility check... or they just got their CMake file wrong (VTKConfigVersion.cmake).

You could do the following:

``` cmake
find_package(VTK 6.1 QUIET)
if (NOT VTK_FOUND)
  find_package(VTK 6.0 QUIET)
  if (NOT VTK_FOUND)
    message (FATAL_ERROR "Could not find VTK 6 or newer. Either install a compatible version or set WITH_VTK to OFF.")
  endif ()
endif ()
```

EDIT: The QUIET may not actually be necessary/wanted. Just no use of REQUIRED is important at least for the first call and the second if you want a custom error message.

**Comment by ghisvail** [comment]
> Was just thinking if they messed sth up in this version and therefore the strict compatibility check... or they just got their CMake file wrong (VTKConfigVersion.cmake).

Neither of those. 

```
# This version is compatible only with matching major.minor versions.
```

This comment says it all, upstream guarantees backward compatibility only for incremental patch versions (so no semver). Then, it makes sense they don't support a check for a minimum version.

**Comment by ghisvail** [comment]
Anyway, we have a fix now. Thanks @stefanpsz for reporting this.

**Comment by schuhschuh** [comment]
Well, ok, but that means code that was built for VTK 6.0 does potentially not work with VTK 6.1. Hence, VTK 6.1 is not fully backwards compatible. Otherwise, your find_package for version "6[.0.0]" would have worked. As it seems to break backwards compatibility with VTK 6.0, I assumed maybe sth in the first major refactored VTK wasn't done right when 6.0 was released...

**Comment by schuhschuh** [comment]
> Anyway, we have a fix now.

I would encourage reconsidering the _fix_ for the same reasons mentioned before... Have you tried the above suggestion?

``` cmake
find_package(VTK 6.1 QUIET)
if (NOT VTK_FOUND)
  find_package(VTK 6.0 QUIET)
  if (NOT VTK_FOUND)
    message (FATAL_ERROR "Could not find VTK 6 or newer. Either install a compatible version or set WITH_VTK to OFF.")
  endif ()
endif ()
```
