### ISSUE TITLE
Do not cache "*_FULL_*DIR" variables

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/irtk-refactored-deprecated#28]
These variables are derived from CMAKE_INSTALL_PREFIX and the respective `IRTK_INSTALL_*DIR` variables. A user should only see and set these variables (the `IRTK_INSTALL_*` variables should be advanced as a normal user should not care about them). When an `IRTK_INSTALL_*DIR` variable is an absolute path, do not prepend the CMAKE_INSTALL_PREFIX, otherwise prepand it to set the `IRTK_INSTALL_FULL_*DIR` variables. Or disallow such out-of-prefix installation path by requiring relative installation paths. Anyway, the `IRTK_INSTALL_FULL_*DIR` auxiliary variables should not show up in the CMake cache.

**Comment by ghisvail** [comment]
sure
