### ISSUE TITLE
Fix vol2mesh and use newer PolyData filters

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/irtk-refactored-deprecated#3]
The vol2mesh source files I copied from Robert are modified by me to compile with VTK 6 and this new version of IRTK. These changes seem to have messed with the code and the vol2mesh tool is not actually functional. Also, Robert has made small improvements to his code since I copied them. A proper integration of the vol2mesh tool should be done together with Robert (either as a separate Package or as part of the PolyData module). The vol2mesh tool further uses Robert's irtkRemeshing filter (slightly modified by me), whereas I since added a newer implementation named irtkPolyDataRemeshing. This implementation should be used by vol2mesh, with the proper settings/modifications to achieve the same result as the irtkRemeshing filter would give. Also, the new irtkPolyDataSmoothing filter could be of interest to remove some "copy-and-pasted" code from irtkVolumeToMesh.

**Comment by schuhschuh** [comment]
The files copied from Robert are (excl. .h/.cc extension):
- vol2mesh
- irtkVolumeToMesh
- irtkParticleSampleSphere
- irtkSphereQuadrisect

The irtkParticleSampleSphere (which uses irtkSphereQuadrisect) implementation is definitely general purpose and should remain in the PolyData module, but requires a bit of refactoring to fit in nicely with the other PolyData filters in this module.

**Comment by ghisvail** [comment]
Feel free to assign yourself to this issue and propose a PR for it. Seems that you are already have a nice solution in mind.

**Comment by schuhschuh** [comment]
As mentioned, these source files are not from me. They have been written by Robert who should be involved in integrating his command-line tool into IRTK (possibly as optional package). I just think that `irtkParticleSampleSphere` could be of general interest and thus be integrated into the PolyData module. But this is not a task I will take care of. Also, as the PolyData module is part of the core libraries, it's functionality should be used by Packages instead. Thus, irtkVolumeToMesh should utilise the PolyData filters where possible. Again, not something on my agenda. I can assist in modifying those filters I wrote if needed, but I will not make vol2mesh fit for release. I am developing my own tools with a broader range of applications for this. As of now, vol2mesh works pretty well and is a crucial part of the dHCP pipeline. Thus, it will need to be available as part of IRTK sooner or later. You should talk to Robert who wrote the code to help him integrate it into IRTK.

Otherwise, I would simply remove aforementioned source files again from the PolyData module (probably anyway the best until Robert's most recent vol2mesh implementation has been integrated properly).

**Comment by ghisvail** [comment]
So just to summarize, the appropriate solution should be to move:
- vol2mesh
- irtkVolumeToMesh
- irtkParticleSampleSphere
- irtkSphereQuadrisect

out of PolyData and discuss with Robert to make it a separate package.

**Comment by schuhschuh** [comment]
Well, the vol2mesh tool kind of yes. But irtkParticleSampleSphere (and thus also irtkSphereQuadrisect as it is used by that class only) would be nice to have in the PolyData library as it would also be useful for other tools. But with only 2 source files left, I just don't know if it is worth making a separate package for it, though I somewhat feel like it should be. But when the code would be refactored the irtkVolumeToMesh file could also become a nice filter that takes a segmentation image as input and produces a genus-0 surface mesh as output.

**Comment by schuhschuh** [comment]
In any case, right now I would remove those files. Then you can coordinate with Robert how to best integrate his tool.
