### ISSUE TITLE
irtkMatrix::operator(): Control may reach end of non-void function

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/irtk-refactored-deprecated#39]
Two of the `irtkMatrix::operator()`'s are missing an `exit(1)` call when the input indices are out of bounds.

**Comment by ghisvail** [comment]
Using `exit` in library code is bad practice, as it leaves little opportunity for client code to do proper clean-up. This is a different issue though and probably not localized only to `irtkMatrix`.

**Comment by schuhschuh** [comment]
Yes, I am fully aware of this, but as it has not been addressed in this version of the code where the practice is to call `exit` to "raise an exception", it makes sense.

**Comment by ghisvail** [comment]
Absolutely.
