### ISSUE TITLE
PolyData applications are not built

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/irtk-refactored-deprecated#5]
The PolyData module contains an `app` subdirectory that does not seem to be included in the build. It should be standardised how to organise the applications. Should they all go into the Applications directory? Maybe in subdirectories? Or some specialised applications be part of an optional Package?

**Comment by ghisvail** [comment]
I have a few ideas regarding how the modules' tree layout should be organized. Regardless, all of them will have access to the `BUILD_APPLICATIONS`, `BUILD_DOCUMENTATION` and `BUILD_TESTING` CMake options. So until, a common layout is agreed, the following can be appended to the PolyData root list file:

```
if(BUILD_APPLICATION)
  add_subdirectory(app)
endif()
```

**Comment by schuhschuh** [comment]
For the current project organization, I would suggest moving the PolyData applications instead to the Applications folder until a proposal for how to organise applications has been agreed on. The Modules should probably contain library code only.

EDIT: I might also remove some of the PolyData applications for now which I don't consider ready for external use.
