### ISSUE TITLE
Considering removing irtkZLib

### ISSUE THREAD

**Issue by schuhschuh** [BioMedIA/irtk-refactored-deprecated#62]
This file contains a single function ReadCompressedBytes which should be obsolete/deprecated. In fact, this function did not work on newer OS X systems. Instead, always use/require ZLib instead to read/write compressed binary data (cf. irtkCifstream and irtkCofstream).

**Comment by ghisvail** [comment]
Indeed, this file only defines `irtkGzFile` and `ReadCompressed`, both of which are not used anywhere else:

```
grep -r irtkGzFile .
./Modules/Common/include/irtkZLib.h:#  define irtkGzFile gzFile
./Modules/Common/include/irtkZLib.h:#  define irtkGzFile FILE*
./Modules/Common/include/irtkZLib.h:int ReadCompressed(irtkGzFile, char *, long, long);
```

```
grep -r ReadCompressed .
./Modules/Common/src/irtkZLib.cc:int ReadCompressed(gzFile file, char *mem, long start, long num)
./Modules/Common/src/irtkZLib.cc:int ReadCompressed(FILE *file, char *mem, long start, long num)
```

So the removal can be safely performed. Good catch.

**Comment by ghisvail** [comment]
Whilst solving this issue I figured that the irtkCifstream and irtkCofstream classes had different signature for the handling of the file attribute:

```
class irtkCifstream : public irtkObject
{
  irtkObjectMacro(irtkCifstream);

  /// File pointer to potentially compressed file
#ifdef HAS_ZLIB
  gzFile _File;
#else
  FILE  *_File;
#endif
```

and

```
class irtkCofstream : public irtkObject
{
  irtkObjectMacro(irtkCofstream);

  /// File pointer to uncompressed file
  FILE *_File;

#ifdef HAS_ZLIB
  /// File pointer to compressed file
  gzFile _ZFile;
#endif
```

Is there a specific reason why? I would have expected the declaration of these classes to be fairly symmetrical.

**Comment by schuhschuh** [comment]
> Is there a specific reason why? I would have expected the declaration of these classes to be fairly symmetrical.

I suppose the output stream has two file pointers because you can decide at runtime whether you want to write to a compressed stream (gzFile) or standard file stream (FILE). See _Compressed flag.
